### ISSUE TITLE
Pull in latest changes from upstream, composer 2 compat

### ISSUE THREAD

**Issue by austinpray** [roots/wordpress-core-installer#2]

**Comment by jstoone** [comment]
Hey @austinpray, don't hesitate giving me a ping, if I can help out with this. If so, then I'll open a PR with the upstream changes. ☺️ ✌️

**Comment by austinpray** [comment]
@jstoone please do! I can help you test it up :+1:

**Comment by jstoone** [comment]
@austinpray I'm sorry for the delay, but life entered the door and my PR dropped on the floor.

But I'm back, and the PR should be ready for you to review. :v:

I've tried writing a few notes down, with any noteworthy changes that one could miss. But please just throw any comments my way and I'll get back to you as soon as I can. ☺️ ✌️

**Comment by austinpray** [comment]
@jstoone Thank you! Will take a look soon here
