### ISSUE TITLE
A new release is needed in order to update packagist and support Composer 2.0

### ISSUE THREAD

**Issue by furins** [roots/wordpress-core-installer#4]
* [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

install worpdress-core-installer now fails because [Composer 2.0 is out](https://blog.packagist.com/composer-2-0-is-now-available/).
Actual version of worpdress-core-installer on packagist.org is 1.1.0 (2018-12-10) so it does not include the recent PR merge #3 (Allow Composer V2).

## Steps to reproduce

1. update composer
2. `composer require roots/wordpress-core-installer`

or run a vanilla trellis install (the issue is blocking the provisioning of new VMs).

**Expected behavior:** 
Package wordpress-core-installer should install.

**Actual behavior:** [What actually happens]
```
$ composer require roots/wordpress-core-installer


  [InvalidArgumentException]
  Package roots/wordpress-core-installer at version  has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version


require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...
```
**Reproduces how often:** 
Always, since 2020-10-24.

**Comment by austinpray** [comment]
The master version of this repo actually contains the proper patches. Just need to tag a release. Will do that today at some point.

**Comment by furins** [comment]
Thank you Austin!

**Comment by austinpray** [comment]
@furins I just released 1.100.0 after a small amount of testing. In your development environment can you try `composer update roots/wordpress-core-installer` performs as you expect under composer 2? Works on my machine:tm:

**Comment by SimJoSt** [comment]
Works for me.

**Comment by furins** [comment]
@austinpray I've checked both in my development environment and with a new trellis install. Everything works smoothly. Thank you!

**Comment by vladolaru** [comment]
@austinpray Could we get that release? Thanks

**Comment by austinpray** [comment]
> @austinpray Could we get that release? Thanks

@vladolaru https://github.com/roots/wordpress-core-installer/issues/4#issuecomment-716227485

**Comment by vladolaru** [comment]
Oh. So it is not version 2.0 but 1.100.0

The things is that in the Readme.md it is `"roots/wordpress-core-installer": "^2.0"`

**Comment by austinpray** [comment]
@vladolaru yeah that's a merge error/oversight when pulling from the upstream. Send a PR to fix and I'll merge it 👍
